name: '✨ Prettier Code Formatter'

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prettier Check
        run: npx prettier --check **/*.md --config .prettierrc
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.md --config .prettierrc
